# Mule ESB instance particulars
server:
    host: "localhost"
    port: 9000
    username: ""
    password: ""

# Mule ESB MBeans
mbeans:
    domainMatcher: "Mule.*"
    types: [org.mule.Statistics]
    excludeDomains: [Mule..agent,Mule.default]

#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Mule ESB|"