# Use this only if SIM is enabled
#metricPrefix: Custom Metrics|Mule ESB|

# If SIM is not enabled, then use this
metricPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|Mule ESB|
#To find the <COMPONENT_ID> in your environment,
#please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java

# Mule ESB instance particulars
servers:
   - displayName: "Mule Server" # mandatory
     serviceUrl: ""
     host: localhost
     port: 1098
     username: ""
     password: ""
     # Mule ESB MBeans
     mbeanDetails:
        domainMatcher: "Mule.*"
        types: [org.mule.Statistics]
        excludeDomains: []
        flows: [.*]


# please add escape charaters "\\" before your value. It changes from OS to OS, some need it, some don't
# For Example, replace: "%" -> Becomes -> replace: "\\%"
metricPathReplacements:
   - replace: "\""
     replaceWith: ""
   - replace: "="
     replaceWith: "|"


# Each server instance needs 1 threads to call the mule ESB.
 # By default we want to support 3 servers, so it is 3 threads.
numberOfThreads: 3


