# Use this only if SIM is enabled
#metricPrefix: "Custom Metrics|Mule ESB|"

# If SIM is not enabled, then use this
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Mule ESB|"
#To find the <COMPONENT_ID> in your environment,
#please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java

# Mule ESB instance particulars
servers:
   - displayName: "Mule Server" # mandatory
      #     You can either use just a host and port to connect or use your full serviceURL to make the connection
      #     Do not choose both, comment one out and only use the other.
#     serviceUrl: ""         #e.g: "service:jmx:rmi:///jndi/rmi://localhost:9000/jmxrmi"
     host: localhost
     port: 9000
     username: ""
     password: ""  #if encryptedPassword is being used, put password as empty.
#     encryptedPassword: ""  #Needs to be used in conjunction with `encryptionKey`. Please read the extension documentation to generate encrypted password. https://community.appdynamics.com/t5/Knowledge-Base/How-do-I-use-Password-Encryption-with-Extensions/ta-p/29397
     # Mule ESB MBeans
     mbeanDetails:
        domainMatcher: "Mule.*"
        types: [org.mule.Statistics]
        excludeDomains: []
        flows: [.*]


# please add escape charaters "\\" before your value. It changes from OS to OS, some need it, some don't
# For Example, replace: "%" -> Becomes -> replace: "\\%"
metricPathReplacements:
   - replace: "\""
     replaceWith: ""
   - replace: "="
     replaceWith: "|"


# Each server instance needs 1 threads to call the mule ESB.
 # By default we want to support 3 servers, so it is 3 threads.
numberOfThreads: 3

controllerInfo:
  controllerHost: ""
  controllerPort: 8080
  account: "customer1"
  username: "user1"
  password: "welcome"
  encryptedPassword: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""

encryptionKey: "abcd"